### ISSUE TITLE
openweathermap terminates with errorcode 0

### ISSUE THREAD

**Issue by mthalhof** [ioBroker/ioBroker.openweathermap#24]
unfortunately there are no more information :-/
my software versions:

Kernel release
4.19.66-v7+
Node openssl version
1.1.1d
OS openssl version
1.1.0l
OpenSSL library
OpenSSL
Node.js version
10.18.1
v8 version
6.8.275.32-node.55
NPM version
6.13.4
Git version
2.11.0
Perl version
5.24.1
Python version
2.7.13
Python3 version
3.5.3
os.pip
19.2.1
os.pip3
19.2.1
Java version
1.8.0_65
GCC version
7.3.0

**Comment by Apollon77** [comment]
you can try to start the adapter using commandline. go to iobroker directory on SSH and execute

node node_modules/ioBroker.openweathermap/main.js --debug

And post the output

**Comment by mthalhof** [comment]
@Apollon77 
many thanks for taking a look - that's the output:
`
2020-02-16 13:07:04.823  - debug: openweathermap.0 (10455) Redis Objects: Use Redis connection: 127.0.0.1:9001

2020-02-16 13:07:04.888  - debug: openweathermap.0 (10455) Objects client ready ... initialize now

2020-02-16 13:07:04.896  - debug: openweathermap.0 (10455) Objects create PubSub Client

2020-02-16 13:07:04.899  - debug: openweathermap.0 (10455) Objects client initialize lua scripts

2020-02-16 13:07:04.926  - debug: openweathermap.0 (10455) objectDB connected

2020-02-16 13:07:04.931  - debug: openweathermap.0 (10455) Redis States: Use Redis connection: 127.0.0.1:9000

2020-02-16 13:07:04.937  - debug: openweathermap.0 (10455) Objects connected to redis: 127.0.0.1:9001

2020-02-16 13:07:04.963  - debug: openweathermap.0 (10455) States create PubSub Client

2020-02-16 13:07:04.966  - debug: openweathermap.0 (10455) statesDB connected

2020-02-16 13:07:05.179  - debug: openweathermap.0 (10455) States connected to redis: 127.0.0.1:9000

2020-02-16 13:07:07.494  - info: openweathermap.0 (10455) starting. Version 0.1.0 in /opt/iobroker/node_modules/iobroker.openweathermap, node: v10.18.1

2020-02-16 13:07:10.927  - info: openweathermap.0 (10455) Terminated (NO_ERROR): Without reason`

**Comment by Apollon77** [comment]
Hm ... no error ... interesting. Evenrything configured correctly?

**Comment by Jakrabo** [comment]
Hello everyone,

I´ve got the same issue. Openweathrmap terminates with code 0 and it doesn´t call the wetherdata. I already tried to set a CRON to restart the adapter every 5 minutes but without success. When I restart the adapter manually it calls the weatherdata one time and then it terminates again.

Any idea what to do?

**Comment by mthalhof** [comment]
Hi Jakrabo,

I don't really figured out why, but my weatherdata Objects get now filled and updated. It still terminates with code 0 and there is also no "green light" at the instance. Maybe this is the intended behaviour to start,get data,terminate.

**Comment by mintert91** [comment]
I have exactly the same problem. No data, no green light.. 

`/opt/iobroker/node_modules $ node iobroker.openweathermap/main.js --debug
2020-04-07 15:55:43.261  - debug: openweathermap.0 (28763) Redis Objects: Use Redis connection: 127.0.0.1:9001
2020-04-07 15:55:43.305  - debug: openweathermap.0 (28763) Objects client ready ... initialize now
2020-04-07 15:55:43.310  - debug: openweathermap.0 (28763) Objects create System PubSub Client
2020-04-07 15:55:43.312  - debug: openweathermap.0 (28763) Objects create User PubSub Client
2020-04-07 15:55:43.313  - debug: openweathermap.0 (28763) Objects client initialize lua scripts
2020-04-07 15:55:43.334  - debug: openweathermap.0 (28763) Objects connected to redis: 127.0.0.1:9001
2020-04-07 15:55:43.358  - debug: openweathermap.0 (28763) objectDB connected
2020-04-07 15:55:43.361  - debug: openweathermap.0 (28763) Redis States: Use Redis connection: 127.0.0.1:9000
2020-04-07 15:55:43.376  - debug: openweathermap.0 (28763) States create User PubSub Client
2020-04-07 15:55:43.379  - debug: openweathermap.0 (28763) States create System PubSub Client
2020-04-07 15:55:43.387  - debug: openweathermap.0 (28763) States connected to redis: 127.0.0.1:9000
2020-04-07 15:55:43.388  - debug: openweathermap.0 (28763) statesDB connected
2020-04-07 15:55:45.312  - info: openweathermap.0 (28763) starting. Version 0.1.0 in /opt/iobroker/node_modules/iobroker.openweathermap, node: v10.18.1
2020-04-07 15:55:49.325  - info: openweathermap.0 (28763) Terminated (NO_ERROR): Without reason`

**Comment by Apollon77** [comment]
Yes, this is a schedule adapter, so it runs in  schedule (e.g. every 30 minutes) and then exists. so whats the problem?

**Comment by mintert91** [comment]
The problem is that the program exits without any error and does nothing.
No values are filled an no sctructure has been created.
![image](https://user-images.githubusercontent.com/7135919/78861092-36881f00-7a34-11ea-936f-ffb968fad33a.png)

**Comment by mintert91** [comment]
After serveral scheduled retries, it is working now. Do not know why... Didn't change anything.

**Comment by Anzic23** [comment]
js-controller 3.0.14
Node.js
v10.20.1 
NPM
6.14.4
```
2020-04-22 22:10:00.030 - info: host.iobroker instance system.adapter.openweathermap.0 started with pid 19053
--
2020-04-22 22:10:03.111 - info: openweathermap.0 (19053) starting. Version 0.1.0 in /opt/iobroker/node_modules/iobroker.openweathermap, node: v10.20.1, js-controller: 3.0.14
2020-04-22 22:10:03.989 - error: openweathermap.0 (19053) uncaught exception: Cannot read property 'statusCode' of undefined
2020-04-22 22:10:03.993 - error: openweathermap.0 (19053) TypeError: Cannot read property 'statusCode' of undefined
at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.openweathermap/main.js:286:47)
at self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
at Request.emit (events.js:198:13)
at Request.onRequestError (/opt/iobroker/node_modules/request/request.js:881:8)
at ClientRequest.emit (events.js:198:13)
at TLSSocket.socketErrorListener (_http_client.js:401:9)
at TLSSocket.emit (events.js:198:13)
at emitErrorNT (internal/streams/destroy.js:91:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
at process._tickCallback (internal/process/next_tick.js:63:19)
2020-04-22 22:10:04.496 - info: openweathermap.0 (19053) terminating
2020-04-22 22:10:04.497 - info: openweathermap.0 (19053) Terminated (NO_ERROR): Without reason
2020-04-22 22:10:05.008 - info: host.iobroker instance system.adapter.openweathermap.0 terminated with code 0 (NO_ERROR)


```

**Comment by lumo2707** [comment]
Any updates to this issue? Still facing the same without any solutions from now.


instance system.adapter.openweathermap.0 terminated with code 0 (NO_ERROR)
--
openweathermap.0 | 2021-06-08 21:03:05.833 | info | (7109) Terminated (NO_ERROR): Without reason
openweathermap.0 | 2021-06-08 21:03:01.652 | info | (7109) starting. Version 0.1.0 in /opt/iobroker/node_modules/iobroker.openweathermap, node: v12.21.0, js-controller: 3.2.16

**Comment by Apollon77** [comment]
@lumo2707 basically as written above. This is the normal log whats the question?

**Comment by olli0815** [comment]
the fact is that the (scheduled) adapter stops restarting / receiving data after a couple of days. 
Restarting it manually a couple of times then let it receive / update the data points again.

That is a sporadic, annoying issue.

**Comment by Apollon77** [comment]
A "terminted 0" is completely normal when it is ready and ends after doing it's work .... So whats exactly the issue/question? Is it maybe not updating values?
